const express = require('express')
const router = express.Router()
const AdminController = require('../controllers/adminController')

router.post('/v1/create-employee', AdminController.createEmployeeAccount)
router.get('/v1/fetch-active-employees', AdminController.fetchAllActiveEmployee)
router.get('/v1/fetch-leave-requests', AdminController.fetchAllRequestLeave)
router.put('/v1/approve-leave-request/:leaveId/:approvedBy', AdminController.approveLeaveRequest)
router.put('/v1/decline-leave-request/:leaveId/:declinedBy', AdminController.declineLeaveRequest)
router.post('/v1/create-new-department/:createdBy', AdminController.createNewDepartment)
router.get('/v1/fetch-departments', AdminController.fetchAllDepartments)
router.post('/v1/add-holiday/:createdBy', AdminController.createHoliday)
router.get('/v1/fetch-all-holidays', AdminController.fetchHolidays)
router.post('/v1/add-schedule-slot/:adminUserId', AdminController.createScheduleSlot)
router.delete('/v1/delete/schedule-slot/:scheduleId', AdminController.deleteScheduleSlot)
router.post('/v1/assign-employee-schedule/:scheduleId/:employeeId', AdminController.assignEmployeeToSchedule)
router.put('/v1/change-assigned-employee/:scheduleId/:employeeId', AdminController.changeAssignedEmployee)
router.get('/v1/fetch-schedule-slots', AdminController.fetchScheduleSlots)

module.exports = router